[package]
name = "chars"
version = "0.1.0"
authors = ["Andreas Fuchs <asf@boinkor.net>"]

exclude = [
        "data/*",
        "generator/*",
]

[dependencies]
unicode_names = { git = 'https://github.com/antifuchs/unicode_names', branch = 'update-to-unicode-8.0' }
unicode-width = "0.1.3"
byteorder = "0.5.3"
lazy_static = "0.2.1"
fst = "0.1"
