[package]
name = "chars"
version = "0.2.0"
authors = ["Andreas Fuchs <asf@boinkor.net>"]

# We use repo crates, crates.io does not want that:
publish = false

exclude = [
        "data/*",
        "generator/*",
]

[dependencies]
unicode_names = { git = 'https://github.com/Jokler/unicode_names', rev = 'd97b80c3c35b9f1d04085409087ef113c94cde17' }
unicode-width = { git = 'https://github.com/lukaramu/unicode-width', rev = '4940d3fe277a6de0ae640411d7d16ec1c76dbbc5' }
byteorder = "1"
lazy_static = "1.0.0"
fst = "0.3.0"
# Only a dependency on nightly rust:
clippy = {version = "*", optional = true}

[features]
default = []
